### ISSUE TITLE
Mucho espacio entre el numero de casilla y las respuestas

### ISSUE THREAD

**Issue by PieroMateo** [yorhg/Trivia_v1#1]
lo unico que podria corregir en tu codigo es el espacio que tienen los numeros con respecto a las respuestas a seleccionar. ejemplo: 1.         python es de facil interpretacion.
![image](https://user-images.githubusercontent.com/113325866/190000367-c27f28d7-2804-4b1f-88d1-b01e597c94b9.png)

**Comment by yorhg** [comment]
Gracias, se solucionó con un comando que limpie la pantalla después de responder. #1
